/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string | number;
export type Title = string;
export type Published = string;
export type Body = string;
export type Author = string;
export type AuthorId = string;
export type LinkedCount = number;
export type LinkTo = string[] | null;
export type Position = number | null;

export interface TextOverView {
  id: Id;
  title: Title;
  published: Published;
  body: Body;
  author: Author;
  author_id: AuthorId;
  linked_count: LinkedCount;
  link_to?: LinkTo;
  position: Position;
  [k: string]: unknown;
}
